version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./example_data/db:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    command: ./script/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

