# Generated by Django 3.2.4 on 2021-06-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XSS', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=4)),
                ('CSRF', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Vul',
            },
        ),
    ]
