# Generated by Django 3.2.3 on 2021-05-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(default='', max_length=10)),
                ('firtName', models.CharField(default='', max_length=7)),
                ('lastName', models.CharField(default='', max_length=7)),
                ('avatar', models.ImageField(upload_to=None)),
                ('status', models.TextField(default='')),
                ('facebook', models.CharField(default='', max_length=200)),
                ('github', models.CharField(default='', max_length=200)),
                ('twitter', models.CharField(default='', max_length=200)),
                ('email', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.user')),
            ],
        ),
    ]
