# Generated by Django 3.2.4 on 2021-06-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_vul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vul',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
