# Generated by Django 3.2.10 on 2021-12-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, max_length=255, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
