# Generated by Django 3.2.3 on 2021-05-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('status', models.TextField(default='')),
                ('creaaTime', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmt_email', to='blogapp.user')),
                ('username', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cmt_user', to='blogapp.user')),
            ],
        ),
    ]
