# Generated by Django 3.2.4 on 2021-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_vul_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vul',
            name='status',
            field=models.BooleanField(),
        ),
    ]
