# Generated by Django 3.2.3 on 2021-05-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('status', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(upload_to=None)),
                ('tags', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.tags')),
                ('username', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.user')),
            ],
        ),
    ]
