# Generated by Django 3.2.3 on 2021-05-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guser', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(blank=True, upload_to=None)),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authors_id', to='guser.guestuser')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
        ),
    ]
