from blogapp.views.index import index
from blogapp.views.blog import blog
from blogapp.views.post import post
from blogapp.views.search import search
from blogapp.views.setting import  setting
from blogapp.views.register import register
from blogapp.views.login import login_view
from blogapp.views.logout import logout_view
from blogapp.views.tags import tags