from blogapp.views.index import indexView
from blogapp.views.blog import blogView
from blogapp.views.post import postView
from blogapp.views.search import searchView
from blogapp.views.setting import settingView
from blogapp.views.register import registerView
from blogapp.views.login import loginView
from blogapp.views.logout import logoutView
from blogapp.views.tags import tagsView
from blogapp.views.profile import profileView
from blogapp.views.contributor import contributorView
from blogapp.views.requestpost import requestpostView
from blogapp.views.previewpost import preView
from blogapp.views.uploads import avatarView
