from blogapp.views.index import indexView
from blogapp.views.blog import blogView
from blogapp.views.post import postView
from blogapp.views.search import search
from blogapp.views.setting import setting
from blogapp.views.register import registerView
from blogapp.views.login import login_view
from blogapp.views.logout import logoutView
from blogapp.views.tags import tagsView
from blogapp.views.validate import validate