# Generated by Django 3.2.3 on 2021-05-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guser', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to=None)),
                ('status', models.BooleanField(default=False)),
                ('creaaTime', models.DateTimeField(auto_now_add=True)),
                ('Post_id', models.ManyToManyField(to='post.Post')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='guser.guestuser')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='guser.guestuser')),
            ],
        ),
    ]
